baseurl: ""

sass:
    load_paths:
        - _sass
        - node_modules

collections:
  banner-section:
  section-titles:
  case-study:
  why-us-cards:
  locusteam:
      output: true
      
exclude: []